# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20151223_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslocation',
            name='label',
            field=models.CharField(default='New location', max_length=200),
        ),
        migrations.AddField(
            model_name='uslocation',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='room'),
        ),
    ]
